
version: 2

build_defaults: &build_defaults
  docker:
    - image: circleci/node:8.11.2
  working_directory: ~/repo

default_steps:
  set_build_attributes: &set_build_attributes
    run:
      name: Set BUILD_NUM, BUILD_BRANCH, VERSION
      command: |
        ./.circleci/set-build-attributes.sh
  setup_docker: &setup_docker
    setup_remote_docker:
      docker_layer_caching: false  # true when feature is enabled
  login_to_dockerhub: &login_to_dockerhub
    run:
      name: Login to docker hub
      command: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS

jobs:
  build:
    <<: *build_defaults
    steps:
      - checkout
      - *set_build_attributes
      - *setup_docker
      - *login_to_dockerhub

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          npm install

      - run:
          npm run build

      - run:
          name: Build docker image
          command: |
            cd deploy
            docker-compose --file docker-compose-circleci.yml build
            docker-compose --file docker-compose-circleci.yml push

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

workflows:
  version: 2
  build-n-deploy:
    jobs:
      # Build and test on all branches and tags
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^re-.*/
      # Push docker images on all branches and release tags
#      - deploy:
#          requires:
#            - build
#          filters:
#            tags:
#              only:
#                - /^release-.*/
